package de.bht.fpa.mail.s797307.util.parser;

public enum SNodeTypes {
  UNION, INTERSECTION, IMPORTANCE, NULL, READ, RECIPIENTS, SENDER, SUBJECT, TEXT, IMPORTANCE_NESTING, READ_NESTING, RECIPIENTS_NESTING, SENDER_NESTING, SUBJECT_NESTIng, TEXT_NESTING;
}
